"""
seed_data.py — заповнення бази даних тестовими товарами

Запускається ОДИН РАЗ:
    python seed_data.py
"""
import json
from database import init_db, get_connection

PRODUCTS = [
    # ── КУРТКИ ────────────────────────────────────────────────────────────────
    {"name": "Куртка вітровка Nike Air", "category": "куртки", "brand": "Nike",
     "price": 3200, "sizes": ["S", "M", "L", "XL"], "colors": ["чорний", "синій"],
     "material": "поліестер", "description": "Легка спортивна вітровка з водовідштовхувальним покриттям",
     "image_url": "https://placehold.co/400x500/1b2a4a/ffffff.png?text=Jacket"},
    {"name": "Зимова пухівка The North Face Nuptse", "category": "куртки", "brand": "The North Face",
     "price": 9500, "sizes": ["S", "M", "L", "XL", "XXL"], "colors": ["чорний", "жовтий"],
     "material": "нейлон", "description": "Легендарна пухова куртка для екстремального холоду",
     "image_url": "https://placehold.co/400x500/1b2a4a/ffffff.png?text=Jacket"},
    {"name": "Зимова куртка Adidas Puffer", "category": "куртки", "brand": "Adidas",
     "price": 4500, "sizes": ["S", "M", "L", "XL", "XXL"], "colors": ["чорний", "сірий"],
     "material": "поліестер", "description": "Тепла зимова куртка з синтетичним наповнювачем",
     "image_url": "https://placehold.co/400x500/1b2a4a/ffffff.png?text=Jacket"},
    {"name": "Джинсова куртка Levi's Trucker", "category": "куртки", "brand": "Levi's",
     "price": 3800, "sizes": ["XS", "S", "M", "L", "XL"], "colors": ["синій", "чорний"],
     "material": "денім", "description": "Класична джинсова куртка, яка ніколи не виходить з моди",
     "image_url": "https://placehold.co/400x500/1b2a4a/ffffff.png?text=Jacket"},
    {"name": "Куртка з екошкіри H&M Biker", "category": "куртки", "brand": "H&M",
     "price": 3800, "sizes": ["S", "M", "L", "XL"], "colors": ["чорний"],
     "material": "шкіра", "description": "Стильна куртка в байкерському стилі з екошкіри",
     "image_url": "https://placehold.co/400x500/1b2a4a/ffffff.png?text=Jacket"},
    {"name": "Парка Zara Water Repellent", "category": "куртки", "brand": "Zara",
     "price": 5200, "sizes": ["S", "M", "L", "XL"], "colors": ["зелений", "чорний"],
     "material": "поліестер", "description": "Подовжена парка з капюшоном та захистом від дощу",
     "image_url": "https://placehold.co/400x500/1b2a4a/ffffff.png?text=Jacket"},
    {"name": "Куртка Tommy Hilfiger Heritage", "category": "куртки", "brand": "Tommy Hilfiger", 
     "price": 6500, "sizes": ["S", "M", "L", "XL"], "colors": ["синій", "червоний"], 
     "material": "бавовна", "description": "Преміум куртка з класичним логотипом",
     "image_url": "https://placehold.co/400x500/1b2a4a/ffffff.png?text=Jacket"},
    {"name": "Бомбер Pull&Bear Military", "category": "куртки", "brand": "Pull&Bear",
     "price": 2900, "sizes": ["M", "L", "XL"], "colors": ["чорний", "хакі"],
     "material": "нейлон", "description": "Міський бомбер у стилі мілітарі",
     "image_url": "https://placehold.co/400x500/1b2a4a/ffffff.png?text=Jacket"},

    # ── ПАЛЬТА ────────────────────────────────────────────────────────────────
    {"name": "Пальто Zara Wool Blend", "category": "пальта", "brand": "Zara",
     "price": 4200, "sizes": ["XS", "S", "M", "L", "XL"], "colors": ["бежевий", "сірий", "чорний"], 
     "material": "вовна", "description": "Елегантне пальто з вовняної суміші, класичний крій",
     "image_url": "https://placehold.co/400x500/3d2b1f/ffffff.png?text=Coat"},
    {"name": "Пальто H&M Oversized", "category": "пальта", "brand": "H&M",
     "price": 2800, "sizes": ["XS", "S", "M", "L"], "colors": ["чорний", "бежевий"], 
     "material": "поліестер", "description": "Модне оверсайз пальто для міського стилю",
     "image_url": "https://placehold.co/400x500/3d2b1f/ffffff.png?text=Coat"},
    {"name": "Пальто Mango Double Breasted", "category": "пальта", "brand": "Mango",
     "price": 5100, "sizes": ["S", "M", "L"], "colors": ["сірий", "чорний"], 
     "material": "вовна", "description": "Двобортне пальто в діловому стилі",
     "image_url": "https://placehold.co/400x500/3d2b1f/ffffff.png?text=Coat"},
    {"name": "Тренч Calvin Klein Classic", "category": "пальта", "brand": "Calvin Klein",
     "price": 6800, "sizes": ["S", "M", "L"], "colors": ["бежевий"],
     "material": "бавовна", "description": "Легкий весняний тренч преміум-якості",
     "image_url": "https://placehold.co/400x500/3d2b1f/ffffff.png?text=Coat"},

    # ── ХУДІ ТА СВІТШОТИ ──────────────────────────────────────────────────────
    {"name": "Худі Nike Tech Fleece", "category": "худі", "brand": "Nike",
     "price": 3800, "sizes": ["S", "M", "L", "XL", "XXL"], "colors": ["чорний", "сірий", "синій"], 
     "material": "поліестер", "description": "Технологічне флісове худі для тренувань та відпочинку",
     "image_url": "https://placehold.co/400x500/2d2d2d/ffffff.png?text=Hoodie"},
    {"name": "Худі Adidas Essentials", "category": "худі", "brand": "Adidas",
     "price": 1900, "sizes": ["XS", "S", "M", "L", "XL", "XXL"], "colors": ["чорний", "білий", "сірий"], 
     "material": "бавовна", "description": "Базове худі Adidas з м'якого бавовняного трикотажу",
     "image_url": "https://placehold.co/400x500/2d2d2d/ffffff.png?text=Hoodie"},
    {"name": "Худі Puma Oversize", "category": "худі", "brand": "Puma",
     "price": 1700, "sizes": ["S", "M", "L"], "colors": ["зелений", "чорний"],
     "material": "бавовна", "description": "Стильне худі вільного крою",
     "image_url": "https://placehold.co/400x500/2d2d2d/ffffff.png?text=Hoodie"},
    {"name": "Худі H&M Relaxed Fit", "category": "худі", "brand": "H&M",
     "price": 850, "sizes": ["XS", "S", "M", "L", "XL"], "colors": ["бежевий", "сірий"], 
     "material": "бавовна", "description": "Зручне повсякденне худі relaxed fit",
     "image_url": "https://placehold.co/400x500/2d2d2d/ffffff.png?text=Hoodie"},
    {"name": "Світшот Vans Classic Crew", "category": "худі", "brand": "Vans",
     "price": 1600, "sizes": ["S", "M", "L", "XL"], "colors": ["чорний", "білий"],
     "material": "бавовна", "description": "Світшот без капюшона зі скейтерським логотипом",
     "image_url": "https://placehold.co/400x500/2d2d2d/ffffff.png?text=Hoodie"},
    {"name": "Худі Pull&Bear Graphic", "category": "худі", "brand": "Pull&Bear",
     "price": 1200, "sizes": ["S", "M", "L", "XL"], "colors": ["чорний", "білий", "рожевий"], 
     "material": "бавовна", "description": "Худі з принтом у вуличному стилі",
     "image_url": "https://placehold.co/400x500/2d2d2d/ffffff.png?text=Hoodie"},

    # ── СВЕТРИ ────────────────────────────────────────────────────────────────
    {"name": "Светр Zara Knit", "category": "светри", "brand": "Zara",
     "price": 1800, "sizes": ["S", "M", "L", "XL"], "colors": ["бежевий", "коричневий", "сірий"], 
     "material": "акрил", "description": "Теплий в'язаний светр, ідеальний для осені",
     "image_url": "https://placehold.co/400x500/5c3d2e/ffffff.png?text=Sweater"},
    {"name": "Светр H&M Merino Blend", "category": "светри", "brand": "H&M",
     "price": 1400, "sizes": ["XS", "S", "M", "L"], "colors": ["чорний", "синій"], 
     "material": "вовна", "description": "Светр з домішкою меріносової вовни",
     "image_url": "https://placehold.co/400x500/5c3d2e/ffffff.png?text=Sweater"},
    {"name": "Светр Tommy Hilfiger Cable", "category": "светри", "brand": "Tommy Hilfiger", 
     "price": 4800, "sizes": ["S", "M", "L", "XL"], "colors": ["білий", "синій"], 
     "material": "бавовна", "description": "Класичний светр з косами від Tommy Hilfiger",
     "image_url": "https://placehold.co/400x500/5c3d2e/ffffff.png?text=Sweater"},
    {"name": "Светр Mango Turtleneck", "category": "светри", "brand": "Mango",
     "price": 2200, "sizes": ["XS", "S", "M", "L"], "colors": ["чорний", "бежевий", "червоний"], 
     "material": "акрил", "description": "Светр з високим горлом (гольф), м'який та теплий",
     "image_url": "https://placehold.co/400x500/5c3d2e/ffffff.png?text=Sweater"},
    {"name": "Кардиган Pull&Bear", "category": "светри", "brand": "Pull&Bear",
     "price": 1500, "sizes": ["S", "M", "L"], "colors": ["сірий", "чорний"],
     "material": "акрил", "description": "Стильний кардиган на ґудзиках",
     "image_url": "https://placehold.co/400x500/5c3d2e/ffffff.png?text=Sweater"},

    # ── ФУТБОЛКИ ТА ПОЛО ──────────────────────────────────────────────────────
    {"name": "Футболка Nike Dri-FIT", "category": "футболки", "brand": "Nike",
     "price": 950, "sizes": ["S", "M", "L", "XL", "XXL"], "colors": ["чорний", "білий", "синій"], 
     "material": "поліестер", "description": "Спортивна футболка з технологією відведення вологи",
     "image_url": "https://placehold.co/400x500/1a4040/ffffff.png?text=T-Shirt"},
    {"name": "Футболка Adidas Trefoil", "category": "футболки", "brand": "Adidas",
     "price": 800, "sizes": ["XS", "S", "M", "L", "XL"], "colors": ["чорний", "білий"], 
     "material": "бавовна", "description": "Класична футболка з логотипом Adidas Originals",
     "image_url": "https://placehold.co/400x500/1a4040/ffffff.png?text=T-Shirt"},
    {"name": "Компресійна футболка Under Armour", "category": "футболки", "brand": "Under Armour",
     "price": 1200, "sizes": ["S", "M", "L", "XL"], "colors": ["чорний"],
     "material": "еластан", "description": "Компресійна футболка для важких тренувань",
     "image_url": "https://placehold.co/400x500/1a4040/ffffff.png?text=T-Shirt"},
    {"name": "Футболка H&M Basic (Набір 3 шт)", "category": "футболки", "brand": "H&M",
     "price": 750, "sizes": ["XS", "S", "M", "L", "XL", "XXL"], "colors": ["чорний", "білий", "сірий"], 
     "material": "бавовна", "description": "Набір базових футболок на кожен день",
     "image_url": "https://placehold.co/400x500/1a4040/ffffff.png?text=T-Shirt"},
    {"name": "Футболка Zara Slim", "category": "футболки", "brand": "Zara",
     "price": 550, "sizes": ["S", "M", "L", "XL"], "colors": ["білий", "чорний", "бежевий"], 
     "material": "бавовна", "description": "Футболка slim fit з якісної бавовни",
     "image_url": "https://placehold.co/400x500/1a4040/ffffff.png?text=T-Shirt"},
    {"name": "Футболка Pull&Bear Oversize", "category": "футболки", "brand": "Pull&Bear", 
     "price": 650, "sizes": ["S", "M", "L", "XL"], "colors": ["чорний", "білий", "сірий"], 
     "material": "бавовна", "description": "Оверсайз футболка у вуличному стилі",
     "image_url": "https://placehold.co/400x500/1a4040/ffffff.png?text=T-Shirt"},
    {"name": "Поло Tommy Hilfiger", "category": "футболки", "brand": "Tommy Hilfiger",
     "price": 2400, "sizes": ["S", "M", "L", "XL"], "colors": ["синій", "білий", "червоний"],
     "material": "бавовна", "description": "Класичне бавовняне поло",
     "image_url": "https://placehold.co/400x500/264040/ffffff.png?text=Polo"},

    # ── ДЖИНСИ ────────────────────────────────────────────────────────────────
    {"name": "Джинси Levi's 501 Original", "category": "джинси", "brand": "Levi's",
     "price": 3800, "sizes": ["S", "M", "L", "XL"], "colors": ["синій", "чорний", "блакитний"],
     "material": "денім", "description": "Еталонні джинси прямого крою",
     "image_url": "https://placehold.co/400x500/1a1a4a/ffffff.png?text=Jeans"},
    {"name": "Джинси Zara Slim Fit", "category": "джинси", "brand": "Zara",
     "price": 1600, "sizes": ["S", "M", "L", "XL"], "colors": ["синій", "чорний"], 
     "material": "денім", "description": "Класичні джинси slim fit з еластичного деніму",
     "image_url": "https://placehold.co/400x500/1a1a4a/ffffff.png?text=Jeans"},
    {"name": "Джинси H&M Relaxed", "category": "джинси", "brand": "H&M",
     "price": 1100, "sizes": ["XS", "S", "M", "L", "XL"], "colors": ["синій", "сірий"], 
     "material": "денім", "description": "Широкі джинси вільного крою",
     "image_url": "https://placehold.co/400x500/1a1a4a/ffffff.png?text=Jeans"},
    {"name": "Джинси Pull&Bear Mom Fit", "category": "джинси", "brand": "Pull&Bear",
     "price": 1300, "sizes": ["XS", "S", "M", "L"], "colors": ["блакитний", "синій"],
     "material": "денім", "description": "Жіночі джинси мом з високою посадкою",
     "image_url": "https://placehold.co/400x500/1a1a4a/ffffff.png?text=Jeans"},
    {"name": "Джинси Tommy Hilfiger Denton", "category": "джинси", "brand": "Tommy Hilfiger", 
     "price": 3500, "sizes": ["S", "M", "L", "XL"], "colors": ["синій"], 
     "material": "денім", "description": "Преміум джинси straight fit",
     "image_url": "https://placehold.co/400x500/1a1a4a/ffffff.png?text=Jeans"},

    # ── ШТАНИ ТА ШОРТИ ────────────────────────────────────────────────────────
    {"name": "Штани Nike Sportswear Joggers", "category": "штани", "brand": "Nike",
     "price": 2200, "sizes": ["S", "M", "L", "XL"], "colors": ["чорний", "сірий"], 
     "material": "поліестер", "description": "Спортивні джогери з манжетами",
     "image_url": "https://placehold.co/400x500/2d331a/ffffff.png?text=Pants"},
    {"name": "Штани Adidas Track", "category": "штани", "brand": "Adidas",
     "price": 1800, "sizes": ["S", "M", "L", "XL", "XXL"], "colors": ["чорний", "синій"], 
     "material": "поліестер", "description": "Класичні спортивні штани з трьома смугами",
     "image_url": "https://placehold.co/400x500/2d331a/ffffff.png?text=Pants"},
    {"name": "Чиноси Zara Comfort", "category": "штани", "brand": "Zara",
     "price": 1400, "sizes": ["S", "M", "L", "XL"], "colors": ["бежевий", "чорний", "синій"], 
     "material": "бавовна", "description": "Елегантні чиноси на кожен день",
     "image_url": "https://placehold.co/400x500/2d331a/ffffff.png?text=Pants"},
    {"name": "Штани H&M Cargo", "category": "штани", "brand": "H&M",
     "price": 1100, "sizes": ["XS", "S", "M", "L", "XL"], "colors": ["чорний", "коричневий", "хакі"], 
     "material": "бавовна", "description": "Штани карго з великими боковими кишенями",
     "image_url": "https://placehold.co/400x500/2d331a/ffffff.png?text=Pants"},
    {"name": "Шорти Nike Pro", "category": "штани", "brand": "Nike",
     "price": 1300, "sizes": ["S", "M", "L"], "colors": ["чорний"],
     "material": "еластан", "description": "Спортивні шорти для тренувань",
     "image_url": "https://placehold.co/400x500/2d3d1a/ffffff.png?text=Shorts"},

    # ── СУКНІ ТА СПІДНИЦІ ─────────────────────────────────────────────────────
    {"name": "Сукня Zara Midi", "category": "сукні", "brand": "Zara",
     "price": 2300, "sizes": ["XS", "S", "M", "L"], "colors": ["чорний", "червоний"], 
     "material": "поліестер", "description": "Елегантна міді-сукня для особливих подій",
     "image_url": "https://placehold.co/400x500/4a1a3d/ffffff.png?text=Dress"},
    {"name": "Сукня H&M Wrap", "category": "сукні", "brand": "H&M",
     "price": 1200, "sizes": ["XS", "S", "M", "L"], "colors": ["чорний", "синій"], 
     "material": "поліестер", "description": "Сукня на запах для офісу та повсякдення",
     "image_url": "https://placehold.co/400x500/4a1a3d/ffffff.png?text=Dress"},
    {"name": "Сукня Mango Satin", "category": "сукні", "brand": "Mango",
     "price": 3200, "sizes": ["XS", "S", "M", "L"], "colors": ["бежевий", "чорний"], 
     "material": "поліестер", "description": "Атласна сукня для вечірнього виходу",
     "image_url": "https://placehold.co/400x500/4a1a3d/ffffff.png?text=Dress"},
    {"name": "Літня сукня Pull&Bear", "category": "сукні", "brand": "Pull&Bear",
     "price": 900, "sizes": ["S", "M", "L"], "colors": ["білий", "жовтий"],
     "material": "льон", "description": "Легка лляна сукня для спекотної погоди",
     "image_url": "https://placehold.co/400x500/4a1a3d/ffffff.png?text=Dress"},

    # ── ВЗУТТЯ ────────────────────────────────────────────────────────────────
    {"name": "Кросівки Nike Air Force 1", "category": "взуття", "brand": "Nike",
     "price": 4200, "sizes": ["38", "39", "40", "41", "42", "43", "44"], "colors": ["білий", "чорний"], 
     "material": "шкіра", "description": "Легендарні міські кросівки зі шкіри",
     "image_url": "https://placehold.co/400x500/401a1a/ffffff.png?text=Shoes"},
    {"name": "Кросівки Nike Pegasus 40", "category": "взуття", "brand": "Nike",
     "price": 4800, "sizes": ["39", "40", "41", "42", "43", "44", "45"], "colors": ["чорний", "синій"],
     "material": "синтетика", "description": "Бігові кросівки з відмінною амортизацією",
     "image_url": "https://placehold.co/400x500/401a1a/ffffff.png?text=Shoes"},
    {"name": "Кросівки Adidas Samba", "category": "взуття", "brand": "Adidas",
     "price": 3800, "sizes": ["37", "38", "39", "40", "41", "42"], "colors": ["білий", "чорний"], 
     "material": "шкіра", "description": "Трендові кросівки в ретро стилі",
     "image_url": "https://placehold.co/400x500/401a1a/ffffff.png?text=Shoes"},
    {"name": "Кросівки New Balance 574", "category": "взуття", "brand": "New Balance", 
     "price": 3500, "sizes": ["39", "40", "41", "42", "43", "44"], "colors": ["сірий", "синій", "зелений"], 
     "material": "синтетика", "description": "Культова модель New Balance на кожен день",
     "image_url": "https://placehold.co/400x500/401a1a/ffffff.png?text=Shoes"},
    {"name": "Кеди Vans Old Skool", "category": "взуття", "brand": "Vans",
     "price": 2800, "sizes": ["38", "39", "40", "41", "42", "43", "44"], "colors": ["чорний"],
     "material": "синтетика", "description": "Класичні скейтерські кеди з білою смугою",
     "image_url": "https://placehold.co/400x500/401a1a/ffffff.png?text=Shoes"},
    {"name": "Черевики Timberland 6-Inch", "category": "взуття", "brand": "Timberland",
     "price": 7500, "sizes": ["40", "41", "42", "43", "44"], "colors": ["жовтий", "коричневий"],
     "material": "шкіра", "description": "Водонепроникні зимові черевики",
     "image_url": "https://placehold.co/400x500/40331a/ffffff.png?text=Boots"},
    {"name": "Черевики H&M Chelsea", "category": "взуття", "brand": "H&M",
     "price": 2200, "sizes": ["39", "40", "41", "42", "43", "44"], "colors": ["чорний", "коричневий"], 
     "material": "шкіра", "description": "Класичні черевики челсі з екошкіри",
     "image_url": "https://placehold.co/400x500/40331a/ffffff.png?text=Boots"},
    {"name": "Сланці Adidas Adilette", "category": "взуття", "brand": "Adidas",
     "price": 1100, "sizes": ["39", "40", "41", "42", "43"], "colors": ["чорний", "синій"],
     "material": "синтетика", "description": "Легкі шльопанці для басейну або пляжу",
     "image_url": "https://placehold.co/400x500/1a3340/ffffff.png?text=Slides"},

    # ── АКСЕСУАРИ ─────────────────────────────────────────────────────────────
    {"name": "Рюкзак Nike Heritage", "category": "аксесуари", "brand": "Nike",
     "price": 1200, "sizes": ["One Size"], "colors": ["чорний", "синій"], 
     "material": "поліестер", "description": "Практичний рюкзак Nike для міста та тренувань",
     "image_url": "https://placehold.co/400x500/1a2640/ffffff.png?text=Backpack"},
    {"name": "Рюкзак The North Face Borealis", "category": "аксесуари", "brand": "The North Face",
     "price": 3500, "sizes": ["One Size"], "colors": ["чорний", "сірий"],
     "material": "нейлон", "description": "Туристичний та міський рюкзак підвищеної міцності",
     "image_url": "https://placehold.co/400x500/1a2640/ffffff.png?text=Backpack"},
    {"name": "Шапка Adidas Beanie", "category": "аксесуари", "brand": "Adidas",
     "price": 500, "sizes": ["One Size"], "colors": ["чорний", "сірий", "білий"], 
     "material": "акрил", "description": "Тепла в'язана шапка з логотипом",
     "image_url": "https://placehold.co/400x500/333340/ffffff.png?text=Beanie"},
    {"name": "Кепка Nike Sportswear", "category": "аксесуари", "brand": "Nike",
     "price": 800, "sizes": ["One Size"], "colors": ["чорний", "білий"],
     "material": "бавовна", "description": "Класична бейсболка з вишитим логотипом",
     "image_url": "https://placehold.co/400x500/262640/ffffff.png?text=Cap"},
    {"name": "Сумка Zara Tote", "category": "аксесуари", "brand": "Zara",
     "price": 1800, "sizes": ["One Size"], "colors": ["чорний", "бежевий", "коричневий"], 
     "material": "шкіра", "description": "Місткий тоут з екошкіри",
     "image_url": "https://placehold.co/400x500/403d1a/ffffff.png?text=Bag"},
    {"name": "Бананка Puma", "category": "аксесуари", "brand": "Puma",
     "price": 750, "sizes": ["One Size"], "colors": ["чорний"],
     "material": "поліестер", "description": "Сумка на пояс для дрібниць",
     "image_url": "https://placehold.co/400x500/403d1a/ffffff.png?text=Bag"},
    {"name": "Ремінь Tommy Hilfiger", "category": "аксесуари", "brand": "Tommy Hilfiger", 
     "price": 1600, "sizes": ["S", "M", "L"], "colors": ["чорний", "коричневий"], 
     "material": "шкіра", "description": "Шкіряний ремінь з фірмовою пряжкою",
     "image_url": "https://placehold.co/400x500/40261a/ffffff.png?text=Belt"},
    {"name": "Шкарпетки Nike Everyday (3 пари)", "category": "аксесуари", "brand": "Nike",
     "price": 600, "sizes": ["M", "L"], "colors": ["білий", "чорний"],
     "material": "бавовна", "description": "Набір високих спортивних шкарпеток",
     "image_url": "https://placehold.co/400x500/333333/ffffff.png?text=Socks"},

         {"name": "Куртка Uniqlo Ultralight Down", "category": "куртки", "brand": "Uniqlo",
     "price": 2400, "sizes": ["XS", "S", "M", "L", "XL", "XXL", "3XL"], "colors": ["чорний", "синій", "червоний"],
     "material": "нейлон", "description": "Ультралегка пухова куртка, що складається в кишеню",
     "image_url": "https://placehold.co/400x500/1b2a4a/ffffff.png?text=Jacket"},
    {"name": "Вітровка Columbia Watertight", "category": "куртки", "brand": "Columbia",
     "price": 3600, "sizes": ["S", "M", "L", "XL", "XXL", "3XL"], "colors": ["чорний", "зелений", "синій"],
     "material": "нейлон", "description": "Водонепроникна вітровка для походів та активного відпочинку",
     "image_url": "https://placehold.co/400x500/1b2a4a/ffffff.png?text=Jacket"},
    {"name": "Куртка Puma Essentials Padded", "category": "куртки", "brand": "Puma",
     "price": 2800, "sizes": ["S", "M", "L", "XL"], "colors": ["чорний", "сірий"],
     "material": "поліестер", "description": "Утеплена спортивна куртка на осінь",
     "image_url": "https://placehold.co/400x500/1b2a4a/ffffff.png?text=Jacket"},
    {"name": "Куртка Mango Quilted", "category": "куртки", "brand": "Mango",
     "price": 4800, "sizes": ["XS", "S", "M", "L"], "colors": ["бежевий", "чорний"],
     "material": "поліестер", "description": "Стьобана жіноча куртка на міжсезоння",
     "image_url": "https://placehold.co/400x500/1b2a4a/ffffff.png?text=Jacket"},
    {"name": "Куртка Patagonia Nano Puff", "category": "куртки", "brand": "Patagonia",
     "price": 8200, "sizes": ["S", "M", "L", "XL", "XXL"], "colors": ["чорний", "синій", "зелений"],
     "material": "нейлон", "description": "Преміум куртка з перероблених матеріалів, надлегка",
     "image_url": "https://placehold.co/400x500/1b2a4a/ffffff.png?text=Jacket"},
    {"name": "Куртка Jack & Jones Puffer", "category": "куртки", "brand": "Jack & Jones",
     "price": 1900, "sizes": ["S", "M", "L", "XL", "XXL"], "colors": ["чорний", "хакі"],
     "material": "поліестер", "description": "Бюджетна зимова пухівка на щодень",
     "image_url": "https://placehold.co/400x500/1b2a4a/ffffff.png?text=Jacket"},
    {"name": "Софтшел The North Face Apex", "category": "куртки", "brand": "The North Face",
     "price": 7200, "sizes": ["S", "M", "L", "XL", "XXL"], "colors": ["чорний", "сірий"],
     "material": "софтшел", "description": "Вітрозахисна софтшел куртка для трекінгу",
     "image_url": "https://placehold.co/400x500/1b2a4a/ffffff.png?text=Jacket"},
    {"name": "Куртка C&A Basic", "category": "куртки", "brand": "C&A",
     "price": 1200, "sizes": ["S", "M", "L", "XL", "XXL", "3XL", "4XL"], "colors": ["чорний", "синій"],
     "material": "поліестер", "description": "Доступна демісезонна куртка великих розмірів",
     "image_url": "https://placehold.co/400x500/1b2a4a/ffffff.png?text=Jacket"},
    {"name": "Куртка Ralph Lauren Windbreaker", "category": "куртки", "brand": "Ralph Lauren",
     "price": 11500, "sizes": ["S", "M", "L", "XL"], "colors": ["синій", "білий"],
     "material": "нейлон", "description": "Преміальна вітровка з вишитим логотипом",
     "image_url": "https://placehold.co/400x500/1b2a4a/ffffff.png?text=Jacket"},
    {"name": "Куртка Cropp Denim Sherpa", "category": "куртки", "brand": "Cropp",
     "price": 1600, "sizes": ["XS", "S", "M", "L", "XL"], "colors": ["блакитний", "чорний"],
     "material": "денім", "description": "Джинсова куртка з хутряною підкладкою шерпа",
     "image_url": "https://placehold.co/400x500/1b2a4a/ffffff.png?text=Jacket"},
 
    # ── ПАЛЬТА (10 шт) ──────────────────────────────────────────────────────
    {"name": "Пальто Massimo Dutti Cashmere", "category": "пальта", "brand": "Massimo Dutti",
     "price": 12500, "sizes": ["S", "M", "L", "XL"], "colors": ["бежевий", "чорний", "сірий"],
     "material": "кашемір", "description": "Розкішне кашемірове пальто преміум-класу",
     "image_url": "https://placehold.co/400x500/3d2b1f/ffffff.png?text=Coat"},
    {"name": "Пальто Pull&Bear Oversize Check", "category": "пальта", "brand": "Pull&Bear",
     "price": 2200, "sizes": ["XS", "S", "M", "L", "XL"], "colors": ["сірий", "коричневий"],
     "material": "поліестер", "description": "Оверсайз пальто в клітинку, молодіжний крій",
     "image_url": "https://placehold.co/400x500/3d2b1f/ffffff.png?text=Coat"},
    {"name": "Пальто Tommy Hilfiger Wool", "category": "пальта", "brand": "Tommy Hilfiger",
     "price": 8500, "sizes": ["S", "M", "L", "XL", "XXL"], "colors": ["синій", "чорний"],
     "material": "вовна", "description": "Класичне вовняне пальто ділового стилю",
     "image_url": "https://placehold.co/400x500/3d2b1f/ffffff.png?text=Coat"},
    {"name": "Тренч Mango Classic", "category": "пальта", "brand": "Mango",
     "price": 4500, "sizes": ["XS", "S", "M", "L"], "colors": ["бежевий", "чорний"],
     "material": "бавовна", "description": "Класичний тренч з поясом на весну-осінь",
     "image_url": "https://placehold.co/400x500/3d2b1f/ffffff.png?text=Coat"},
    {"name": "Пальто C&A Long Coat", "category": "пальта", "brand": "C&A",
     "price": 1800, "sizes": ["S", "M", "L", "XL", "XXL", "3XL"], "colors": ["чорний", "сірий"],
     "material": "поліестер", "description": "Довге бюджетне пальто для великих розмірів",
     "image_url": "https://placehold.co/400x500/3d2b1f/ffffff.png?text=Coat"},
    {"name": "Пальто Uniqlo Wool Blend", "category": "пальта", "brand": "Uniqlo",
     "price": 3400, "sizes": ["XS", "S", "M", "L", "XL", "XXL"], "colors": ["чорний", "коричневий", "бежевий"],
     "material": "вовна", "description": "Мінімалістичне пальто з вовняної суміші",
     "image_url": "https://placehold.co/400x500/3d2b1f/ffffff.png?text=Coat"},
    {"name": "Шуба H&M Faux Fur", "category": "пальта", "brand": "H&M",
     "price": 3600, "sizes": ["XS", "S", "M", "L"], "colors": ["бежевий", "білий"],
     "material": "еко-хутро", "description": "Пальто зі штучного хутра для ефектного вигляду",
     "image_url": "https://placehold.co/400x500/3d2b1f/ffffff.png?text=Coat"},
    {"name": "Пальто Ralph Lauren Peacoat", "category": "пальта", "brand": "Ralph Lauren",
     "price": 14000, "sizes": ["S", "M", "L", "XL"], "colors": ["синій", "чорний"],
     "material": "вовна", "description": "Двобортне пальто-бушлат преміум-класу",
     "image_url": "https://placehold.co/400x500/3d2b1f/ffffff.png?text=Coat"},
    {"name": "Пальто Jack & Jones Wool", "category": "пальта", "brand": "Jack & Jones",
     "price": 2600, "sizes": ["S", "M", "L", "XL", "XXL"], "colors": ["сірий", "чорний", "синій"],
     "material": "вовна", "description": "Молодіжне вовняне пальто середньої довжини",
     "image_url": "https://placehold.co/400x500/3d2b1f/ffffff.png?text=Coat"},
    {"name": "Пальто Cropp Short Coat", "category": "пальта", "brand": "Cropp",
     "price": 1400, "sizes": ["XS", "S", "M", "L", "XL"], "colors": ["чорний", "бежевий"],
     "material": "поліестер", "description": "Коротке демісезонне пальто за доступною ціною",
     "image_url": "https://placehold.co/400x500/3d2b1f/ffffff.png?text=Coat"},
 
    # ── ХУДІ ТА СВІТШОТИ (10 шт) ────────────────────────────────────────────
    {"name": "Худі Champion Reverse Weave", "category": "худі", "brand": "Champion",
     "price": 2800, "sizes": ["S", "M", "L", "XL", "XXL"], "colors": ["сірий", "синій", "бордовий"],
     "material": "бавовна", "description": "Культове худі з щільного французького трикотажу",
     "image_url": "https://placehold.co/400x500/2d2d2d/ffffff.png?text=Hoodie"},
    {"name": "Худі Uniqlo Dry Stretch", "category": "худі", "brand": "Uniqlo",
     "price": 1500, "sizes": ["XS", "S", "M", "L", "XL", "XXL", "3XL"], "colors": ["чорний", "сірий", "синій"],
     "material": "поліестер", "description": "Легке спортивне худі з швидким висиханням",
     "image_url": "https://placehold.co/400x500/2d2d2d/ffffff.png?text=Hoodie"},
    {"name": "Худі Tommy Hilfiger Logo", "category": "худі", "brand": "Tommy Hilfiger",
     "price": 4200, "sizes": ["S", "M", "L", "XL"], "colors": ["сірий", "синій", "білий"],
     "material": "бавовна", "description": "Преміум худі з великим вишитим логотипом",
     "image_url": "https://placehold.co/400x500/2d2d2d/ffffff.png?text=Hoodie"},
    {"name": "Світшот Zara Basic Crew", "category": "худі", "brand": "Zara",
     "price": 900, "sizes": ["XS", "S", "M", "L", "XL"], "colors": ["чорний", "білий", "бежевий"],
     "material": "бавовна", "description": "Базовий світшот без капюшона на кожен день",
     "image_url": "https://placehold.co/400x500/2d2d2d/ffffff.png?text=Sweatshirt"},
    {"name": "Худі Under Armour Rival Fleece", "category": "худі", "brand": "Under Armour",
     "price": 2400, "sizes": ["S", "M", "L", "XL", "XXL", "3XL"], "colors": ["чорний", "сірий"],
     "material": "поліестер", "description": "Тепле флісове худі для тренувань у прохолоду",
     "image_url": "https://placehold.co/400x500/2d2d2d/ffffff.png?text=Hoodie"},
    {"name": "Худі C&A Oversized", "category": "худі", "brand": "C&A",
     "price": 650, "sizes": ["S", "M", "L", "XL", "XXL", "3XL", "4XL"], "colors": ["чорний", "рожевий", "сірий"],
     "material": "бавовна", "description": "Бюджетне оверсайз худі для великих розмірів",
     "image_url": "https://placehold.co/400x500/2d2d2d/ffffff.png?text=Hoodie"},
    {"name": "Худі Ralph Lauren Bear", "category": "худі", "brand": "Ralph Lauren",
     "price": 6800, "sizes": ["S", "M", "L", "XL"], "colors": ["сірий", "синій"],
     "material": "бавовна", "description": "Колекційне худі з принтом ведмедика Polo Bear",
     "image_url": "https://placehold.co/400x500/2d2d2d/ffffff.png?text=Hoodie"},
    {"name": "Худі Cropp Print", "category": "худі", "brand": "Cropp",
     "price": 750, "sizes": ["XS", "S", "M", "L", "XL"], "colors": ["чорний", "білий"],
     "material": "бавовна", "description": "Молодіжне худі з графічним принтом",
     "image_url": "https://placehold.co/400x500/2d2d2d/ffffff.png?text=Hoodie"},
    {"name": "Світшот Mango Cotton", "category": "худі", "brand": "Mango",
     "price": 1800, "sizes": ["XS", "S", "M", "L"], "colors": ["бежевий", "зелений", "чорний"],
     "material": "бавовна", "description": "Жіночий світшот з органічної бавовни",
     "image_url": "https://placehold.co/400x500/2d2d2d/ffffff.png?text=Sweatshirt"},
    {"name": "Худі Jack & Jones Basic", "category": "худі", "brand": "Jack & Jones",
     "price": 1100, "sizes": ["S", "M", "L", "XL", "XXL"], "colors": ["чорний", "синій", "сірий"],
     "material": "бавовна", "description": "Просте зручне худі на кожен день",
     "image_url": "https://placehold.co/400x500/2d2d2d/ffffff.png?text=Hoodie"},
 
    # ── СВЕТРИ (10 шт) ──────────────────────────────────────────────────────
    {"name": "Светр Uniqlo Cashmere V-Neck", "category": "светри", "brand": "Uniqlo",
     "price": 3200, "sizes": ["XS", "S", "M", "L", "XL", "XXL"], "colors": ["чорний", "бежевий", "синій"],
     "material": "кашемір", "description": "Легкий кашеміровий светр з V-подібним вирізом",
     "image_url": "https://placehold.co/400x500/5c3d2e/ffffff.png?text=Sweater"},
    {"name": "Светр Ralph Lauren Cable Knit", "category": "светри", "brand": "Ralph Lauren",
     "price": 7500, "sizes": ["S", "M", "L", "XL"], "colors": ["білий", "синій", "зелений"],
     "material": "бавовна", "description": "Класичний светр з косами від Polo Ralph Lauren",
     "image_url": "https://placehold.co/400x500/5c3d2e/ffffff.png?text=Sweater"},
    {"name": "Светр C&A Basic Round Neck", "category": "светри", "brand": "C&A",
     "price": 550, "sizes": ["S", "M", "L", "XL", "XXL", "3XL", "4XL"], "colors": ["чорний", "сірий", "синій"],
     "material": "акрил", "description": "Найдоступніший базовий светр великих розмірів",
     "image_url": "https://placehold.co/400x500/5c3d2e/ffffff.png?text=Sweater"},
    {"name": "Светр Massimo Dutti Merino", "category": "светри", "brand": "Massimo Dutti",
     "price": 4200, "sizes": ["S", "M", "L", "XL"], "colors": ["бежевий", "бордовий", "чорний"],
     "material": "вовна", "description": "Елегантний светр з 100% меріносової вовни",
     "image_url": "https://placehold.co/400x500/5c3d2e/ffffff.png?text=Sweater"},
    {"name": "Светр Cropp Oversized", "category": "светри", "brand": "Cropp",
     "price": 800, "sizes": ["XS", "S", "M", "L", "XL"], "colors": ["бежевий", "рожевий", "сірий"],
     "material": "акрил", "description": "Молодіжний оверсайз светр за мінімальну ціну",
     "image_url": "https://placehold.co/400x500/5c3d2e/ffffff.png?text=Sweater"},
    {"name": "Кардиган H&M Long", "category": "светри", "brand": "H&M",
     "price": 1200, "sizes": ["XS", "S", "M", "L", "XL"], "colors": ["сірий", "чорний", "бежевий"],
     "material": "акрил", "description": "Подовжений кардиган на ґудзиках для міжсезоння",
     "image_url": "https://placehold.co/400x500/5c3d2e/ffffff.png?text=Sweater"},
    {"name": "Светр Jack & Jones Knit Crew", "category": "светри", "brand": "Jack & Jones",
     "price": 1500, "sizes": ["S", "M", "L", "XL", "XXL"], "colors": ["чорний", "зелений", "синій"],
     "material": "бавовна", "description": "Чоловічий в'язаний светр з круглим вирізом",
     "image_url": "https://placehold.co/400x500/5c3d2e/ffffff.png?text=Sweater"},
    {"name": "Гольф Zara Ribbed", "category": "светри", "brand": "Zara",
     "price": 1100, "sizes": ["XS", "S", "M", "L", "XL"], "colors": ["чорний", "білий", "коричневий"],
     "material": "віскоза", "description": "Тонкий рубчастий гольф для багатошарових образів",
     "image_url": "https://placehold.co/400x500/5c3d2e/ffffff.png?text=Sweater"},
    {"name": "Кардиган Mango Wool Blend", "category": "светри", "brand": "Mango",
     "price": 3100, "sizes": ["XS", "S", "M", "L"], "colors": ["бежевий", "чорний"],
     "material": "вовна", "description": "Жіночий вовняний кардиган преміум якості",
     "image_url": "https://placehold.co/400x500/5c3d2e/ffffff.png?text=Sweater"},
    {"name": "Светр Calvin Klein Slim", "category": "светри", "brand": "Calvin Klein",
     "price": 5200, "sizes": ["S", "M", "L", "XL"], "colors": ["чорний", "сірий"],
     "material": "вовна", "description": "Мінімалістичний светр slim fit з мериносу",
     "image_url": "https://placehold.co/400x500/5c3d2e/ffffff.png?text=Sweater"},
 
    # ── ФУТБОЛКИ ТА ПОЛО (10 шт) ────────────────────────────────────────────
    {"name": "Футболка Uniqlo Supima Cotton", "category": "футболки", "brand": "Uniqlo",
     "price": 450, "sizes": ["XS", "S", "M", "L", "XL", "XXL", "3XL"], "colors": ["білий", "чорний", "сірий", "синій"],
     "material": "бавовна", "description": "Преміум бавовняна футболка за мінімальну ціну",
     "image_url": "https://placehold.co/400x500/1a4040/ffffff.png?text=T-Shirt"},
    {"name": "Футболка Ralph Lauren Crew", "category": "футболки", "brand": "Ralph Lauren",
     "price": 2800, "sizes": ["S", "M", "L", "XL"], "colors": ["білий", "чорний", "синій"],
     "material": "бавовна", "description": "Преміальна футболка з вишитим логотипом поло",
     "image_url": "https://placehold.co/400x500/1a4040/ffffff.png?text=T-Shirt"},
    {"name": "Футболка C&A 2-Pack Basic", "category": "футболки", "brand": "C&A",
     "price": 350, "sizes": ["S", "M", "L", "XL", "XXL", "3XL", "4XL"], "colors": ["білий", "чорний"],
     "material": "бавовна", "description": "Набір з 2 базових футболок, доступні великі розміри",
     "image_url": "https://placehold.co/400x500/1a4040/ffffff.png?text=T-Shirt"},
    {"name": "Поло Lacoste Classic Fit", "category": "футболки", "brand": "Lacoste",
     "price": 3600, "sizes": ["S", "M", "L", "XL", "XXL"], "colors": ["білий", "синій", "зелений", "червоний"],
     "material": "бавовна", "description": "Класичне поло з фірмовим крокодилом",
     "image_url": "https://placehold.co/400x500/264040/ffffff.png?text=Polo"},
    {"name": "Футболка Levi's Graphic Tee", "category": "футболки", "brand": "Levi's",
     "price": 1100, "sizes": ["XS", "S", "M", "L", "XL"], "colors": ["білий", "чорний", "сірий"],
     "material": "бавовна", "description": "Футболка з культовим логотипом Levi's",
     "image_url": "https://placehold.co/400x500/1a4040/ffffff.png?text=T-Shirt"},
    {"name": "Футболка Champion Logo", "category": "футболки", "brand": "Champion",
     "price": 1300, "sizes": ["S", "M", "L", "XL", "XXL"], "colors": ["білий", "чорний", "сірий", "червоний"],
     "material": "бавовна", "description": "Бавовняна футболка зі знаковим логотипом Champion",
     "image_url": "https://placehold.co/400x500/1a4040/ffffff.png?text=T-Shirt"},
    {"name": "Футболка Mango Linen Blend", "category": "футболки", "brand": "Mango",
     "price": 1050, "sizes": ["XS", "S", "M", "L", "XL"], "colors": ["білий", "бежевий", "оливковий"],
     "material": "льон", "description": "Літня футболка з домішкою льону, дихає в спеку",
     "image_url": "https://placehold.co/400x500/1a4040/ffffff.png?text=T-Shirt"},
    {"name": "Футболка Cropp Longline", "category": "футболки", "brand": "Cropp",
     "price": 400, "sizes": ["XS", "S", "M", "L", "XL"], "colors": ["чорний", "білий", "хакі"],
     "material": "бавовна", "description": "Подовжена футболка у вуличному стилі",
     "image_url": "https://placehold.co/400x500/1a4040/ffffff.png?text=T-Shirt"},
    {"name": "Поло Calvin Klein Slim", "category": "футболки", "brand": "Calvin Klein",
     "price": 2600, "sizes": ["S", "M", "L", "XL"], "colors": ["чорний", "білий", "сірий"],
     "material": "бавовна", "description": "Елегантне поло slim fit для офісу та повсякдення",
     "image_url": "https://placehold.co/400x500/264040/ffffff.png?text=Polo"},
    {"name": "Футболка Jack & Jones Organic", "category": "футболки", "brand": "Jack & Jones",
     "price": 600, "sizes": ["S", "M", "L", "XL", "XXL"], "colors": ["чорний", "білий", "синій", "зелений"],
     "material": "бавовна", "description": "Футболка з органічної бавовни, відповідальне виробництво",
     "image_url": "https://placehold.co/400x500/1a4040/ffffff.png?text=T-Shirt"},
 
    # ── ДЖИНСИ (10 шт) ──────────────────────────────────────────────────────
    {"name": "Джинси Levi's 511 Slim", "category": "джинси", "brand": "Levi's",
     "price": 3200, "sizes": ["28", "30", "32", "34", "36", "38", "40"], "colors": ["синій", "чорний"],
     "material": "денім", "description": "Вузькі джинси slim fit з еластаном, числові розміри",
     "image_url": "https://placehold.co/400x500/1a1a4a/ffffff.png?text=Jeans"},
    {"name": "Джинси Wrangler Regular Fit", "category": "джинси", "brand": "Wrangler",
     "price": 2400, "sizes": ["30", "32", "34", "36", "38", "40", "42"], "colors": ["синій", "темно-синій"],
     "material": "денім", "description": "Класичні прямі джинси для роботи та відпочинку",
     "image_url": "https://placehold.co/400x500/1a1a4a/ffffff.png?text=Jeans"},
    {"name": "Джинси C&A Loose Fit", "category": "джинси", "brand": "C&A",
     "price": 800, "sizes": ["S", "M", "L", "XL", "XXL", "3XL"], "colors": ["синій", "сірий"],
     "material": "денім", "description": "Вільні бюджетні джинси великих розмірів",
     "image_url": "https://placehold.co/400x500/1a1a4a/ffffff.png?text=Jeans"},
    {"name": "Джинси Mango Wide Leg", "category": "джинси", "brand": "Mango",
     "price": 2100, "sizes": ["XS", "S", "M", "L"], "colors": ["блакитний", "білий"],
     "material": "денім", "description": "Жіночі широкі джинси з високою посадкою",
     "image_url": "https://placehold.co/400x500/1a1a4a/ffffff.png?text=Jeans"},
    {"name": "Джинси Calvin Klein Slim Taper", "category": "джинси", "brand": "Calvin Klein",
     "price": 4500, "sizes": ["30", "32", "34", "36", "38"], "colors": ["синій", "чорний"],
     "material": "денім", "description": "Преміум звужені джинси з відмінною посадкою",
     "image_url": "https://placehold.co/400x500/1a1a4a/ffffff.png?text=Jeans"},
    {"name": "Джинси Cropp Skinny", "category": "джинси", "brand": "Cropp",
     "price": 700, "sizes": ["XS", "S", "M", "L", "XL"], "colors": ["чорний", "сірий", "синій"],
     "material": "денім", "description": "Вузькі стрейч-джинси за найнижчою ціною",
     "image_url": "https://placehold.co/400x500/1a1a4a/ffffff.png?text=Jeans"},
    {"name": "Джинси Jack & Jones Glenn Slim", "category": "джинси", "brand": "Jack & Jones",
     "price": 1800, "sizes": ["28", "30", "32", "34", "36", "38"], "colors": ["синій", "чорний", "сірий"],
     "material": "денім", "description": "Популярна slim модель з еластичного деніму",
     "image_url": "https://placehold.co/400x500/1a1a4a/ffffff.png?text=Jeans"},
    {"name": "Джинси Ralph Lauren Sullivan Slim", "category": "джинси", "brand": "Ralph Lauren",
     "price": 5800, "sizes": ["30", "32", "34", "36"], "colors": ["синій", "темно-синій"],
     "material": "денім", "description": "Преміум джинси з японського деніму",
     "image_url": "https://placehold.co/400x500/1a1a4a/ffffff.png?text=Jeans"},
    {"name": "Джинси Uniqlo Ultra Stretch", "category": "джинси", "brand": "Uniqlo",
     "price": 1400, "sizes": ["XS", "S", "M", "L", "XL", "XXL", "3XL"], "colors": ["синій", "чорний", "сірий"],
     "material": "денім", "description": "Джинси з максимальним стрейчем, як леггінси",
     "image_url": "https://placehold.co/400x500/1a1a4a/ffffff.png?text=Jeans"},
    {"name": "Джинси Massimo Dutti Tapered", "category": "джинси", "brand": "Massimo Dutti",
     "price": 3800, "sizes": ["30", "32", "34", "36", "38"], "colors": ["синій", "чорний"],
     "material": "денім", "description": "Елегантні звужені джинси для офісного casual",
     "image_url": "https://placehold.co/400x500/1a1a4a/ffffff.png?text=Jeans"},
 
    # ── ШТАНИ ТА ШОРТИ (10 шт) ──────────────────────────────────────────────
    {"name": "Штани Adidas Tiro Training", "category": "штани", "brand": "Adidas",
     "price": 2400, "sizes": ["S", "M", "L", "XL", "XXL"], "colors": ["чорний", "синій"],
     "material": "поліестер", "description": "Тренувальні штани з клімат-технологією Aeroready",
     "image_url": "https://placehold.co/400x500/2d331a/ffffff.png?text=Pants"},
    {"name": "Чиноси Massimo Dutti Slim", "category": "штани", "brand": "Massimo Dutti",
     "price": 3500, "sizes": ["30", "32", "34", "36", "38"], "colors": ["бежевий", "синій", "чорний"],
     "material": "бавовна", "description": "Преміум чиноси slim fit для ділового стилю",
     "image_url": "https://placehold.co/400x500/2d331a/ffffff.png?text=Pants"},
    {"name": "Штани C&A Linen", "category": "штани", "brand": "C&A",
     "price": 900, "sizes": ["S", "M", "L", "XL", "XXL", "3XL"], "colors": ["білий", "бежевий"],
     "material": "льон", "description": "Легкі лляні штани на спекотне літо, великі розміри",
     "image_url": "https://placehold.co/400x500/2d331a/ffffff.png?text=Pants"},
    {"name": "Штани Under Armour Sport", "category": "штани", "brand": "Under Armour",
     "price": 2200, "sizes": ["S", "M", "L", "XL", "XXL"], "colors": ["чорний", "сірий"],
     "material": "поліестер", "description": "Спортивні штани з технологією відведення вологи",
     "image_url": "https://placehold.co/400x500/2d331a/ffffff.png?text=Pants"},
    {"name": "Шорти H&M Chino", "category": "штани", "brand": "H&M",
     "price": 700, "sizes": ["XS", "S", "M", "L", "XL", "XXL"], "colors": ["бежевий", "синій", "чорний"],
     "material": "бавовна", "description": "Бавовняні шорти-чиноси для літнього повсякдення",
     "image_url": "https://placehold.co/400x500/2d3d1a/ffffff.png?text=Shorts"},
    {"name": "Шорти Puma Training", "category": "штани", "brand": "Puma",
     "price": 1100, "sizes": ["S", "M", "L", "XL"], "colors": ["чорний", "сірий", "синій"],
     "material": "поліестер", "description": "Спортивні шорти для бігу та тренувань",
     "image_url": "https://placehold.co/400x500/2d3d1a/ffffff.png?text=Shorts"},
    {"name": "Штани Pull&Bear Wide Leg", "category": "штани", "brand": "Pull&Bear",
     "price": 1300, "sizes": ["XS", "S", "M", "L", "XL"], "colors": ["чорний", "бежевий", "сірий"],
     "material": "поліестер", "description": "Широкі штани палаццо у трендовому крої",
     "image_url": "https://placehold.co/400x500/2d331a/ffffff.png?text=Pants"},
    {"name": "Класичні штани Tommy Hilfiger", "category": "штани", "brand": "Tommy Hilfiger",
     "price": 4200, "sizes": ["30", "32", "34", "36", "38"], "colors": ["чорний", "синій", "сірий"],
     "material": "вовна", "description": "Вовняні класичні штани для ділового образу",
     "image_url": "https://placehold.co/400x500/2d331a/ffffff.png?text=Pants"},
    {"name": "Джогери Cropp Basic", "category": "штани", "brand": "Cropp",
     "price": 600, "sizes": ["XS", "S", "M", "L", "XL"], "colors": ["чорний", "сірий"],
     "material": "бавовна", "description": "Бюджетні бавовняні джогери для дому та прогулянок",
     "image_url": "https://placehold.co/400x500/2d331a/ffffff.png?text=Pants"},
    {"name": "Шорти Ralph Lauren Swim", "category": "штани", "brand": "Ralph Lauren",
     "price": 3200, "sizes": ["S", "M", "L", "XL"], "colors": ["синій", "червоний", "зелений"],
     "material": "поліестер", "description": "Пляжні шорти з вишитим логотипом",
     "image_url": "https://placehold.co/400x500/2d3d1a/ffffff.png?text=Shorts"},
 
    # ── СУКНІ ТА СПІДНИЦІ (10 шт) ───────────────────────────────────────────
    {"name": "Сукня Zara Shirt Dress", "category": "сукні", "brand": "Zara",
     "price": 1800, "sizes": ["XS", "S", "M", "L", "XL"], "colors": ["білий", "синій"],
     "material": "бавовна", "description": "Сукня-сорочка з поясом, офіс та повсякдення",
     "image_url": "https://placehold.co/400x500/4a1a3d/ffffff.png?text=Dress"},
    {"name": "Сукня Massimo Dutti Knit", "category": "сукні", "brand": "Massimo Dutti",
     "price": 5500, "sizes": ["XS", "S", "M", "L"], "colors": ["бежевий", "чорний", "сірий"],
     "material": "вовна", "description": "В'язана сукня-міді з поясом, преміум якість",
     "image_url": "https://placehold.co/400x500/4a1a3d/ffffff.png?text=Dress"},
    {"name": "Сукня C&A Jersey", "category": "сукні", "brand": "C&A",
     "price": 650, "sizes": ["S", "M", "L", "XL", "XXL", "3XL"], "colors": ["чорний", "синій"],
     "material": "бавовна", "description": "Базова трикотажна сукня, великі розміри",
     "image_url": "https://placehold.co/400x500/4a1a3d/ffffff.png?text=Dress"},
    {"name": "Сукня Tommy Hilfiger Fit & Flare", "category": "сукні", "brand": "Tommy Hilfiger",
     "price": 4800, "sizes": ["XS", "S", "M", "L", "XL"], "colors": ["синій", "червоний", "білий"],
     "material": "бавовна", "description": "Жіночна сукня з розкльошеною спідницею",
     "image_url": "https://placehold.co/400x500/4a1a3d/ffffff.png?text=Dress"},
    {"name": "Спідниця Zara Pleated Midi", "category": "сукні", "brand": "Zara",
     "price": 1500, "sizes": ["XS", "S", "M", "L"], "colors": ["чорний", "бежевий"],
     "material": "поліестер", "description": "Плісирована спідниця-міді на резинці",
     "image_url": "https://placehold.co/400x500/4a1a3d/ffffff.png?text=Skirt"},
    {"name": "Сукня Mango Maxi Linen", "category": "сукні", "brand": "Mango",
     "price": 2800, "sizes": ["XS", "S", "M", "L"], "colors": ["білий", "бежевий"],
     "material": "льон", "description": "Довга лляна сукня для літнього відпочинку",
     "image_url": "https://placehold.co/400x500/4a1a3d/ffffff.png?text=Dress"},
    {"name": "Спідниця H&M Denim Mini", "category": "сукні", "brand": "H&M",
     "price": 800, "sizes": ["XS", "S", "M", "L", "XL"], "colors": ["блакитний", "чорний"],
     "material": "денім", "description": "Коротка джинсова спідниця на літо",
     "image_url": "https://placehold.co/400x500/4a1a3d/ffffff.png?text=Skirt"},
    {"name": "Сукня Calvin Klein Slip Dress", "category": "сукні", "brand": "Calvin Klein",
     "price": 4200, "sizes": ["XS", "S", "M", "L"], "colors": ["чорний", "білий"],
     "material": "поліестер", "description": "Мінімалістична сукня-комбінація у стилі 90-х",
     "image_url": "https://placehold.co/400x500/4a1a3d/ffffff.png?text=Dress"},
    {"name": "Сукня Cropp Mini Bodycon", "category": "сукні", "brand": "Cropp",
     "price": 500, "sizes": ["XS", "S", "M", "L"], "colors": ["чорний", "рожевий"],
     "material": "еластан", "description": "Коротка облягаюча сукня для вечірок",
     "image_url": "https://placehold.co/400x500/4a1a3d/ffffff.png?text=Dress"},
    {"name": "Сукня Ralph Lauren Polo Dress", "category": "сукні", "brand": "Ralph Lauren",
     "price": 6500, "sizes": ["XS", "S", "M", "L", "XL"], "colors": ["синій", "рожевий", "білий"],
     "material": "бавовна", "description": "Бавовняна сукня-поло для спортивного стилю",
     "image_url": "https://placehold.co/400x500/4a1a3d/ffffff.png?text=Dress"},
 
    # ── ВЗУТТЯ (10 шт) ──────────────────────────────────────────────────────
    {"name": "Кросівки Puma RS-X", "category": "взуття", "brand": "Puma",
     "price": 4200, "sizes": ["37", "38", "39", "40", "41", "42", "43", "44", "45", "46"], "colors": ["білий", "чорний", "синій"],
     "material": "синтетика", "description": "Масивні кросівки у стилі ретро з технологією RS",
     "image_url": "https://placehold.co/400x500/401a1a/ffffff.png?text=Shoes"},
    {"name": "Кросівки Converse Chuck Taylor", "category": "взуття", "brand": "Converse",
     "price": 2400, "sizes": ["36", "37", "38", "39", "40", "41", "42", "43", "44", "45"], "colors": ["білий", "чорний", "червоний"],
     "material": "текстиль", "description": "Легендарні високі кеди, які всім пасують",
     "image_url": "https://placehold.co/400x500/401a1a/ffffff.png?text=Shoes"},
    {"name": "Кросівки Reebok Classic Leather", "category": "взуття", "brand": "Reebok",
     "price": 3200, "sizes": ["38", "39", "40", "41", "42", "43", "44", "45"], "colors": ["білий", "чорний"],
     "material": "шкіра", "description": "Культові білі шкіряні кросівки 80-х",
     "image_url": "https://placehold.co/400x500/401a1a/ffffff.png?text=Shoes"},
    {"name": "Кросівки Adidas Ultraboost", "category": "взуття", "brand": "Adidas",
     "price": 6800, "sizes": ["39", "40", "41", "42", "43", "44", "45", "46"], "colors": ["чорний", "білий"],
     "material": "синтетика", "description": "Преміум бігові кросівки з технологією Boost",
     "image_url": "https://placehold.co/400x500/401a1a/ffffff.png?text=Shoes"},
    {"name": "Черевики Dr. Martens 1460", "category": "взуття", "brand": "Dr. Martens",
     "price": 7200, "sizes": ["36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46"], "colors": ["чорний", "вишневий"],
     "material": "шкіра", "description": "Іконічні шкіряні черевики на шнурівці",
     "image_url": "https://placehold.co/400x500/40331a/ffffff.png?text=Boots"},
    {"name": "Кросівки ASICS Gel-Kayano", "category": "взуття", "brand": "ASICS",
     "price": 5500, "sizes": ["39", "40", "41", "42", "43", "44", "45", "46", "47"], "colors": ["чорний", "сірий", "синій"],
     "material": "синтетика", "description": "Професійні бігові кросівки з гелевою амортизацією",
     "image_url": "https://placehold.co/400x500/401a1a/ffffff.png?text=Shoes"},
    {"name": "Мокасини H&M Suede", "category": "взуття", "brand": "H&M",
     "price": 1200, "sizes": ["40", "41", "42", "43", "44"], "colors": ["коричневий", "бежевий"],
     "material": "замш", "description": "Замшеві мокасини для повсякденного носіння",
     "image_url": "https://placehold.co/400x500/40331a/ffffff.png?text=Shoes"},
    {"name": "Туфлі Zara Derby", "category": "взуття", "brand": "Zara",
     "price": 2800, "sizes": ["39", "40", "41", "42", "43", "44", "45"], "colors": ["чорний", "коричневий"],
     "material": "шкіра", "description": "Класичні шкіряні дербі для ділового стилю",
     "image_url": "https://placehold.co/400x500/40331a/ffffff.png?text=Shoes"},
    {"name": "Кросівки C&A Basic Sneaker", "category": "взуття", "brand": "C&A",
     "price": 800, "sizes": ["36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46"], "colors": ["білий", "чорний"],
     "material": "синтетика", "description": "Найдоступніші білі кросівки великого розмірного ряду",
     "image_url": "https://placehold.co/400x500/401a1a/ffffff.png?text=Shoes"},
    {"name": "Босоніжки Mango Leather Sandal", "category": "взуття", "brand": "Mango",
     "price": 2200, "sizes": ["36", "37", "38", "39", "40", "41"], "colors": ["чорний", "бежевий", "білий"],
     "material": "шкіра", "description": "Шкіряні босоніжки на плоскій підошві для літа",
     "image_url": "https://placehold.co/400x500/401a1a/ffffff.png?text=Shoes"},
 
    # ── АКСЕСУАРИ (10 шт) ───────────────────────────────────────────────────
    {"name": "Рюкзак Adidas Classic", "category": "аксесуари", "brand": "Adidas",
     "price": 1500, "sizes": ["One Size"], "colors": ["чорний", "синій", "рожевий"],
     "material": "поліестер", "description": "Спортивний рюкзак Adidas з відділенням для ноутбука",
     "image_url": "https://placehold.co/400x500/1a2640/ffffff.png?text=Backpack"},
    {"name": "Сумка Calvin Klein Crossbody", "category": "аксесуари", "brand": "Calvin Klein",
     "price": 4200, "sizes": ["One Size"], "colors": ["чорний", "білий"],
     "material": "шкіра", "description": "Компактна сумка через плече з преміум екошкіри",
     "image_url": "https://placehold.co/400x500/403d1a/ffffff.png?text=Bag"},
    {"name": "Шарф Zara Wool", "category": "аксесуари", "brand": "Zara",
     "price": 1200, "sizes": ["One Size"], "colors": ["сірий", "бежевий", "чорний"],
     "material": "вовна", "description": "Теплий вовняний шарф для зими",
     "image_url": "https://placehold.co/400x500/333340/ffffff.png?text=Scarf"},
    {"name": "Рюкзак Herschel Little America", "category": "аксесуари", "brand": "Herschel",
     "price": 3800, "sizes": ["One Size"], "colors": ["чорний", "сірий", "синій"],
     "material": "поліестер", "description": "Стильний міський рюкзак з відділенням для ноутбука 15 дюймів",
     "image_url": "https://placehold.co/400x500/1a2640/ffffff.png?text=Backpack"},
    {"name": "Кепка Adidas Baseball Cap", "category": "аксесуари", "brand": "Adidas",
     "price": 650, "sizes": ["One Size"], "colors": ["чорний", "білий", "синій"],
     "material": "бавовна", "description": "Класична бейсболка з вишитим логотипом трилисник",
     "image_url": "https://placehold.co/400x500/262640/ffffff.png?text=Cap"},
    {"name": "Гаманець Tommy Hilfiger", "category": "аксесуари", "brand": "Tommy Hilfiger",
     "price": 2200, "sizes": ["One Size"], "colors": ["чорний", "коричневий"],
     "material": "шкіра", "description": "Шкіряний гаманець з фірмовою стрічкою",
     "image_url": "https://placehold.co/400x500/40261a/ffffff.png?text=Wallet"},
    {"name": "Окуляри Ray-Ban Wayfarer", "category": "аксесуари", "brand": "Ray-Ban",
     "price": 5500, "sizes": ["One Size"], "colors": ["чорний", "коричневий"],
     "material": "пластик", "description": "Культові сонцезахисні окуляри Wayfarer",
     "image_url": "https://placehold.co/400x500/333333/ffffff.png?text=Sunglasses"},
    {"name": "Рукавички H&M Leather", "category": "аксесуари", "brand": "H&M",
     "price": 900, "sizes": ["S/M", "L/XL"], "colors": ["чорний", "коричневий"],
     "material": "шкіра", "description": "Утеплені рукавички з екошкіри на флісі",
     "image_url": "https://placehold.co/400x500/333340/ffffff.png?text=Gloves"},
    {"name": "Годинник Casio F-91W", "category": "аксесуари", "brand": "Casio",
     "price": 850, "sizes": ["One Size"], "colors": ["чорний"],
     "material": "пластик", "description": "Легендарний цифровий годинник — класика на всі часи",
     "image_url": "https://placehold.co/400x500/333333/ffffff.png?text=Watch"},
    {"name": "Сумка Mango Shopper", "category": "аксесуари", "brand": "Mango",
     "price": 1800, "sizes": ["One Size"], "colors": ["чорний", "бежевий", "коричневий"],
     "material": "шкіра", "description": "Велика сумка-шопер з екошкіри для покупок та роботи",
     "image_url": "https://placehold.co/400x500/403d1a/ffffff.png?text=Bag"},
]


def seed():
    init_db()

    with get_connection() as conn:
        count = conn.execute("SELECT COUNT(*) FROM products").fetchone()[0]
        if count > 0:
            print(f"БД вже містить {count} товарів. Пропускаю seed.")
            return

        for p in PRODUCTS:
            conn.execute(
                """INSERT INTO products
                   (name, category, brand, price, sizes, colors,
                    material, description, image_url)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                (p["name"], p["category"], p["brand"], p["price"],
                 json.dumps(p["sizes"], ensure_ascii=False),
                 json.dumps(p["colors"], ensure_ascii=False),
                 p["material"], p["description"], p.get("image_url", ""))
            )

    print(f"✅ Додано {len(PRODUCTS)} товарів у базу даних.")


if __name__ == "__main__":
    seed()
